### ISSUE TITLE
TokenResponse.parseJsonObject(TokenResponse.java:93)

### ISSUE THREAD

**Issue by GerryBennett-TexasMutual** [srempfer/spring-cloud-config-azure-keyvault#33]
Recently tried to use the project and got the following exception

java.lang.NoSuchMethodError: net.minidev.json.JSONObject.getAsNumber(Ljava/lang/String;)Ljava/lang/Number;

I was able to resolve it by upgrading to azure.spring-boot.version 2.3.2 and adding the configuration changes for the new API calls for src/main/java/org/srempfer/cloud/config/keyvault/autoconfigure/KeyVaultAutoConfiguration.java. 

The parameter caseSentative was added to  com.microsoft.azure.keyvault.spring.KeyVaultOperation

Enclosed are the files I updated.
[files.zip](https://github.com/srempfer/spring-cloud-config-azure-keyvault/files/4860895/files.zip)

**Comment by srempfer** [comment]
issue is solved by #31

**Comment by GerryBennett-TexasMutual** [comment]
Any idea when the new official version will be released and jar is available in Maven Central ? Thanks!

**Comment by srempfer** [comment]
I planed the next release for the end of this week

**Comment by srempfer** [comment]
@GerryBennett-TexasMutual: The release 0.4.0 is published now on Maven Central
